packages:
  - "app"
  - "api"

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  bcrypt: true
  core-js: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - zod@4.6.5
