---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Products
- type: directory
  path: content/products
  label: Products
  create: all
  match: "**/*"
  templates:
  - product
- type: heading
  label: Blog
- type: directory
  path: content/blog
  label: Post
  create: documents
  match: "*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: All Pages
- type: document
  path: content/submit.md
  label: Submit
- type: document
  path: content/contact.md
  label: Contact
- type: document
  path: content/terms-conditions.md
  label: Terms Conditions
- type: document
  path: content/privacy-policy.md
  label: Privacy Policy
- type: heading
  label: Configuration
- type: document
  path: config.toml
  label: Configuration
upload_dir: static/products
public_path: static/products
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.78.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.78.1
